### ISSUE TITLE
Inefficient Token Guess

### ISSUE THREAD

**Issue by Itzbenz** [o7-Fire/discord-projects#1]
![image](https://user-images.githubusercontent.com/49940811/161925638-ea4daf25-a2a1-423f-b570-0bea4d31a82a.png)

Use http request instead using 3rd party library 
https://discord.com/developers/docs/resources/user#get-current-user

**Comment by NexitySecond** [comment]
ok i will assign ben to it

**Comment by garylkz** [comment]
seriously

**Comment by Itzbenz** [comment]
Not Fixed

**Comment by garylkz** [comment]
Token guess is illegal

**Comment by Itzbenz** [comment]
Who are you

**Comment by Itzbenz** [comment]
I just want to fix perfomance issue

**Comment by Itzbenz** [comment]
legality is beyond this scope

**Comment by garylkz** [comment]
Actually, this sounds fun. Challenge accepted

**Comment by garylkz** [comment]
But seriously, SEPARATE THE PROJECT WITH 2DMC

**Comment by Itzbenz** [comment]
who

**Comment by Itzbenz** [comment]
Fixed db5f2bdcff5af69bd9aa878e384343c902b84705
